# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6603d1dace1c74c21dd8250b5b8b896f3b08426b0b61a459a7adedd6c620063c5002fb6027a4ac1eafa57d519e4046303a4dc31d2818ad38cbb7348522f0d186

test:
  secret_key_base: 2ce9cf295aff1423ac44599776c8cdbd29b94a5c581f34a6a98a16a9c4b3478162dd41c8367520384a37b999fc7f87bc81641f4319f234059abd5ad7a1a3095a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
